# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
   - node_modules/

variables:
  S3_BUCKET_NAME_PROD: utulsa-assets
  URL_PROD: maps.utulsa.edu
  S3_BUCKET_NAME_DEV: utulsa-assets
  URL_DEV: d1oqrhcv6o35k6.cloudfront.net

stages:
  - setup
  - test
  - build
  - deploy

setup:
  type: setup
  script:
    - npm install

test:
  type: test
  script:
    - npm test

build for production:
  type: build
  only:
    - master
  artifacts:
    paths:
      - build/
  script:
    - npm run build -- --homepage="https://$URL_PROD"

deploy to production:
  type: deploy
  image: python:latest
  only:
    - master
  dependencies:
    - build for production
  environment:
    name: production
    url: https://$URL_DEV/web/map/prod/index.html
  script:
    - pip install awscli
    - aws s3 rm s3://$S3_BUCKET_NAME_PROD/web/map/prod/ --recursive
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME_PROD/web/map/prod/ --recursive
    - curl $PROD_MAPS_UPDATE_URL

build for staging:
  type: build
  only:
    - develop
  artifacts:
    paths:
      - build/
  script:
    - npm run build -- --homepage="https://$URL_DEV/web/map/staging"

deploy to staging:
  type: deploy
  image: python:latest
  only:
    - develop
  dependencies:
    - build for staging
  environment:
    name: staging
    url: https://$URL_DEV/web/map/staging/index.html
  script:
    - pip install awscli
    - aws s3 rm s3://$S3_BUCKET_NAME_DEV/web/map/staging/ --recursive
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME_DEV/web/map/staging/ --recursive

build for review:
  type: build
  except:
    - master
    - develop
  artifacts:
    paths:
      - build/
  script:
    - npm run build -- --homepage="https://$URL_DEV/web/map/review/$CI_BUILD_REF_SLUG"

deploy to review:
  type: deploy
  image: python:latest
  when: manual
  except:
    - master
    - develop
  dependencies:
    - build for review
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$URL_DEV/web/map/review/$CI_BUILD_REF_SLUG/index.html
    on_stop: stop review
  script:
    - pip install awscli
    - aws s3 rm s3://$S3_BUCKET_NAME_DEV/web/map/review/$CI_BUILD_REF_SLUG/ --recursive
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME_DEV/web/map/review/$CI_BUILD_REF_SLUG/ --recursive
    - echo https://$S3_BUCKET_NAME_DEV.s3.amazonaws.com/web/map/review/$CI_BUILD_REF_SLUG/index.html

stop review:
  type: deploy
  image: python:latest
  when: manual
  except:
    - master
    - develop
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  script:
    - pip install awscli
    - aws s3 rm s3://$S3_BUCKET_NAME_DEV/web/map/review/$CI_BUILD_REF_SLUG/ --recursive
