# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
   - node_modules/

variables:
  S3_BUCKET_NAME: utulsa-assets

stages:
  - setup
  - test
  - build
  - deploy

setup:
  type: setup
  script:
    - npm install

test:
  type: test
  script:
    - npm test

build:
  type: build
  script:
    - npm run build

deploy to prod:
  type: deploy
  image: python:latest
  only:
    - master
  environment:
    name: production
    url: https://utulsa-assets.s3.amazonaws.com/web/map/prod/index.html
  script:
    - pip install awscli
    - echo $S3_BUCKET_NAME
    - aws s3 cp ./build/ s3://$S3_BUCKET_NAME/web/map/prod --recursive

# deploy to staging:
#   type: deploy
#   image: python:latest
#   when: manual
#   except:
#     - master
#   environment:
#     name: review/$CI_BUILD_REF_NAME
#   script:
#     - cp build/* public/

# clean up staging:
#   type: deploy
#   image: python:latest
#   when: manual
#   environment:
#     name: review/$CI_BUILD_REF_NAME
#   script:
#     - pip install awscli
#     - aws s3 rm s3://$S3_BUCKET_NAME/web/map/dev/$CI_ENVIRONMENT_SLUG --recursive
