# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

stages:
  - setup
  - test
  - deploy

# setup:
#   type: setup
#   script:
#     - npm install

test:
  type: test
  script:
   - npm install
   - npm test

deploy-prod:
  type: deploy
  only: master
  script:
    - npm run build

# staging:
#   type: deploy
#   environment:
#     name: staging/$CI_BUILD_REF_NAME
#     url: https://$CI_ENVIRONMENT_SLUG.utulsa.co/
#   script:
